services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_ID=1
      - NEXT_NODE_IP=node2
    networks:
      ring_net:
        ipv4_address: 172.20.0.2
    command: ["token_ring.py", "172.20.0.2"]

  node2:
    build: .
    container_name: node2
    depends_on: ["node1"]
    environment:
      - NODE_ID=2
      - NEXT_NODE_IP=node3
    networks:
      ring_net:
        ipv4_address: 172.20.0.3
    command: ["token_ring.py", "172.20.0.3"]

  node3:
    build: .
    container_name: node3
    depends_on: ["node2"]
    environment:
      - NODE_ID=3
      - NEXT_NODE_IP=node4
    networks:
      ring_net:
        ipv4_address: 172.20.0.4
    command: ["token_ring.py", "172.20.0.4"]

  node4:
    build: .
    container_name: node4
    depends_on: ["node3"]
    environment:
      - NODE_ID=4
      - NEXT_NODE_IP=node5
    networks:
      ring_net:
        ipv4_address: 172.20.0.5
    command: ["token_ring.py", "172.20.0.5"]

  node5:
    build: .
    container_name: node5
    depends_on: ["node4"]
    environment:
      - NODE_ID=5
      - NEXT_NODE_IP=node1
    networks:
      ring_net:
        ipv4_address: 172.20.0.6
    command: ["token_ring.py", "172.20.0.6"]

networks:
  ring_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
