networks:
  zeromq_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/16
services:
  node1:
    build: .
    command:
    - leader_selection.py
    - '1'
    - tcp://172.28.1.1:5555
    - '1'
    - tcp://172.28.1.2:5555
    - '2'
    - tcp://172.28.1.3:5555
    - '3'
    - tcp://172.28.1.4:5555
    - '4'
    - tcp://172.28.1.5:5555
    - '5'
    container_name: node1
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.1
  node2:
    build: .
    command:
    - leader_selection.py
    - '2'
    - tcp://172.28.1.2:5555
    - '0'
    - tcp://172.28.1.1:5555
    - '1'
    - tcp://172.28.1.3:5555
    - '3'
    - tcp://172.28.1.4:5555
    - '4'
    - tcp://172.28.1.5:5555
    - '5'
    container_name: node2
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.2
  node3:
    build: .
    command:
    - leader_selection.py
    - '3'
    - tcp://172.28.1.3:5555
    - '0'
    - tcp://172.28.1.1:5555
    - '1'
    - tcp://172.28.1.2:5555
    - '2'
    - tcp://172.28.1.4:5555
    - '4'
    - tcp://172.28.1.5:5555
    - '5'
    container_name: node3
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.3
  node4:
    build: .
    command:
    - leader_selection.py
    - '4'
    - tcp://172.28.1.4:5555
    - '0'
    - tcp://172.28.1.1:5555
    - '1'
    - tcp://172.28.1.2:5555
    - '2'
    - tcp://172.28.1.3:5555
    - '3'
    - tcp://172.28.1.5:5555
    - '5'
    container_name: node4
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.4
  node5:
    build: .
    command:
    - leader_selection.py
    - '5'
    - tcp://172.28.1.5:5555
    - '0'
    - tcp://172.28.1.1:5555
    - '1'
    - tcp://172.28.1.2:5555
    - '2'
    - tcp://172.28.1.3:5555
    - '3'
    - tcp://172.28.1.4:5555
    - '4'
    container_name: node5
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.5
version: '3.8'
