version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.1
    command: ["leader_selection.py", "1", "tcp://172.28.1.1:5555", "tcp://172.28.1.2:5555", "2", "tcp://172.28.1.3:5555", "3"]

  node2:
    build: .
    container_name: node2
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.2
    command: ["leader_selection.py", "2", "tcp://172.28.1.2:5555", "tcp://172.28.1.1:5555", "1", "tcp://172.28.1.3:5555", "3"]

  node3:
    build: .
    container_name: node3
    networks:
      zeromq_net:
        ipv4_address: 172.28.1.3
    command: ["leader_selection.py", "3", "tcp://172.28.1.3:5555", "tcp://172.28.1.1:5555", "1", "tcp://172.28.1.2:5555", "2"]

networks:
  zeromq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
