networks:
  lamport_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/16
services:
  node1:
    build: .
    command:
    - lamport_clock.py
    - tcp://172.28.1.1:5555
    - tcp://172.28.1.2:5555
    - tcp://172.28.1.3:5555
    - tcp://172.28.1.4:5555
    - tcp://172.28.1.5:5555
    container_name: node1
    networks:
      lamport_net:
        ipv4_address: 172.28.1.1
    restart: always
  node2:
    build: .
    command:
    - lamport_clock.py
    - tcp://172.28.1.2:5555
    - tcp://172.28.1.1:5555
    - tcp://172.28.1.3:5555
    - tcp://172.28.1.4:5555
    - tcp://172.28.1.5:5555
    container_name: node2
    networks:
      lamport_net:
        ipv4_address: 172.28.1.2
    restart: always
  node3:
    build: .
    command:
    - lamport_clock.py
    - tcp://172.28.1.3:5555
    - tcp://172.28.1.1:5555
    - tcp://172.28.1.2:5555
    - tcp://172.28.1.4:5555
    - tcp://172.28.1.5:5555
    container_name: node3
    networks:
      lamport_net:
        ipv4_address: 172.28.1.3
    restart: always
  node4:
    build: .
    command:
    - lamport_clock.py
    - tcp://172.28.1.4:5555
    - tcp://172.28.1.1:5555
    - tcp://172.28.1.2:5555
    - tcp://172.28.1.3:5555
    - tcp://172.28.1.5:5555
    container_name: node4
    networks:
      lamport_net:
        ipv4_address: 172.28.1.4
    restart: always
  node5:
    build: .
    command:
    - lamport_clock.py
    - tcp://172.28.1.5:5555
    - tcp://172.28.1.1:5555
    - tcp://172.28.1.2:5555
    - tcp://172.28.1.3:5555
    - tcp://172.28.1.4:5555
    container_name: node5
    networks:
      lamport_net:
        ipv4_address: 172.28.1.5
    restart: always
version: '3.8'
